# Header
menu:
  主页: /
  存档: /archives

# Content
fancybox: true
more_link: true

# Miscellaneous
google_analytics:
google_analytics_4:
favicon: images/vercel.png

# Automatically excerpt description in homepage as preamble text.
excerpt_description: true
